# Generated by Django 5.0.3 on 2024-04-13 07:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_diray'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diray',
            new_name='Diary',
        ),
    ]
